Repository CHADBUCK13/soen341, pull requests merged in 2022-03, with the labels that each got.

#72 Dany reset password/auth
  .gitignore
  .venv/project/ecommerce/databaseContext.py
  main.js
Labels: backend

#73 Refactored docker and fixed credentials for tests
  .circleci/config.yml
  .dockerignore
  .venv/project/.dockerignore
  .venv/project/Dockerfile
  .venv/project/db.sqlite3
  .venv/project/docker-compose.yml
  .venv/project/ecommerce/api/itembrowsing.py
  .venv/project/ecommerce/tests/test_views.py
  .venv/project/project/settings.py
  .venv/project/requirements.txt
  docker-compose.yml
Labels: refactor

#83 UI/frontend/Itembrowsing-Improvements
  .venv/project/docker-compose.yml
  .venv/project/ecommerce/api/itembrowsing.py
  .venv/project/ecommerce/controllers/itemBrowsing/itemBrowsingViews.py
  .venv/project/ecommerce/static/css/mainStyle.css
  .venv/project/ecommerce/templates/baseLayout.html
  .venv/project/ecommerce/templates/home.html
  .venv/project/ecommerce/views.py
Labels: user story, frontend

#90 Improved shopping cart UI and added Order frontend
  .venv/project/.vscode/settings.json
  .venv/project/ecommerce/admin.py
  .venv/project/ecommerce/api/accountContext.py
  .venv/project/ecommerce/api/account_context.py
  .venv/project/ecommerce/api/bankingInfo.py
  .venv/project/ecommerce/api/checkingOut.py
  .venv/project/ecommerce/api/checking_out.py
  .venv/project/ecommerce/api/itembrowsing.py
  .venv/project/ecommerce/api/shoppingCart.py
  .venv/project/ecommerce/controllers/account/accountViews.py
  .venv/project/ecommerce/controllers/banking/bankingViews.py
  .venv/project/ecommerce/controllers/itemBrowsing/itemBrowsingViews.py
  .venv/project/ecommerce/controllers/shoppingCart/orderViews.py
  .venv/project/ecommerce/controllers/shoppingCart/shoppingCartViews.py
  .venv/project/ecommerce/databaseContext.py
  .venv/project/ecommerce/models/address.py
  .venv/project/ecommerce/models/buyer.py
  .venv/project/ecommerce/models/items.py
  .venv/project/ecommerce/models/order.py
  .venv/project/ecommerce/models/paymentInfo.py
  .venv/project/ecommerce/models/paymentInformation.py
  .venv/project/ecommerce/models/payment_information.py
  .venv/project/ecommerce/models/seller.py
  .venv/project/ecommerce/models/user.py
  .venv/project/ecommerce/static/css/mainStyle.css
  .venv/project/ecommerce/templates/baseLayout.html
  .venv/project/ecommerce/templates/home.html
  .venv/project/ecommerce/templates/order_confirmation_email.html
  .venv/project/ecommerce/templates/orders.html
  .venv/project/ecommerce/templates/shoppingCart.html
  .venv/project/ecommerce/tests/test_api.py
  .venv/project/ecommerce/tests/test_models.py
  .venv/project/ecommerce/tests/test_views.py
  .venv/project/ecommerce/urls.py
  .venv/project/static/resources/Mastercard_logo.jpg
  .venv/project/static/resources/VISA-logo.png
Labels: frontend, feature

#91 Removed unecessary files and directories
  .venv/project/ecommerce/.venv/silx/third_party/_local/scipy_spatial/qhull/COPYING.txt
  .venv/project/ecommerce/databaseContext.py
  .venv/project/ecommerce/tests/test_views.py
Labels: refactor
